import "./globals.css";

export const metadata = {
  title: "Les cochers solidaires",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className="flex justify-center">{children}</body>
    </html>
  );
}
